"""
Authentication Dialog
Supports both headers-auth and OAuth flows.
"""
from __future__ import annotations

import os
import webbrowser

from PyQt6.QtCore import Qt, QSize
from PyQt6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QLabel,
    QPushButton, QTabWidget, QWidget, QLineEdit,
    QTextEdit, QFileDialog, QMessageBox, QFrame,
)


class AuthDialog(QDialog):
    """
    Modal dialog to authenticate with YouTube Music.
    Two methods:
      1. Browser Cookie / Request Headers (paste headers)
      2. OAuth (client_id + client_secret)
    """

    def __init__(self, config_dir: str, parent=None):
        super().__init__(parent)
        self.config_dir   = config_dir
        self.auth_path    = os.path.join(config_dir, "browser.json")
        self.oauth_path   = os.path.join(config_dir, "oauth.json")
        self.result_path: str | None = None

        self.setWindowTitle("Sign In to YouTube Music")
        self.setMinimumWidth(500)
        self.setMinimumHeight(420)
        self._build_ui()

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(20, 20, 20, 20)
        root.setSpacing(12)

        title = QLabel("Sign In to YouTube Music")
        title.setStyleSheet("font-size: 16px; font-weight: bold;")
        root.addWidget(title)

        sub = QLabel(
            "Choose an authentication method. "
            "Your credentials are stored locally and never transmitted anywhere."
        )
        sub.setWordWrap(True)
        root.addWidget(sub)

        tabs = QTabWidget()
        root.addWidget(tabs)

        # ---- Tab 1: Browser headers ----
        headers_tab = QWidget()
        hl = QVBoxLayout(headers_tab)
        hl.setSpacing(8)

        step1 = QLabel(
            "<b>Step 1</b> — Open <a href='https://music.youtube.com'>music.youtube.com</a> "
            "and sign in."
        )
        step1.setOpenExternalLinks(True)
        step1.setWordWrap(True)
        hl.addWidget(step1)

        step2 = QLabel(
            "<b>Step 2</b> — Open DevTools (F12 → Network tab), play any song, "
            "right-click the first request to <code>music.youtube.com</code> → "
            "<i>Copy → Copy request headers</i>."
        )
        step2.setWordWrap(True)
        hl.addWidget(step2)

        step3 = QLabel("<b>Step 3</b> — Paste the headers below:")
        hl.addWidget(step3)

        self._headers_edit = QTextEdit()
        self._headers_edit.setPlaceholderText(":authority: music.youtube.com\n:method: GET\ncookie: ...")
        self._headers_edit.setAcceptRichText(False)
        hl.addWidget(self._headers_edit)

        save_headers_btn = QPushButton("Save && Sign In")
        save_headers_btn.setDefault(True)
        save_headers_btn.clicked.connect(self._save_headers)
        hl.addWidget(save_headers_btn)

        tabs.addTab(headers_tab, "Browser Headers")

        # ---- Tab 2: File ----
        file_tab = QWidget()
        fl = QVBoxLayout(file_tab)
        fl.setSpacing(8)

        fl.addWidget(QLabel(
            "If you already have a <code>browser.json</code> or <code>oauth.json</code> "
            "generated by ytmusicapi, select it here."
        ))

        pick_btn = QPushButton("Browse for auth file…")
        pick_btn.clicked.connect(self._pick_file)
        fl.addWidget(pick_btn)

        self._file_label = QLabel("No file selected")
        self._file_label.setStyleSheet("color: gray;")
        fl.addWidget(self._file_label)

        self._use_file_btn = QPushButton("Use Selected File")
        self._use_file_btn.setEnabled(False)
        self._use_file_btn.clicked.connect(self._use_file)
        fl.addWidget(self._use_file_btn)

        fl.addStretch()
        tabs.addTab(file_tab, "Existing Auth File")

        # ---- Buttons ----
        btn_row = QHBoxLayout()
        cancel_btn = QPushButton("Cancel")
        cancel_btn.clicked.connect(self.reject)
        btn_row.addStretch()
        btn_row.addWidget(cancel_btn)
        root.addLayout(btn_row)

    # ------------------------------------------------------------------

    def _save_headers(self):
        raw = self._headers_edit.toPlainText().strip()
        if not raw:
            QMessageBox.warning(self, "Empty", "Please paste your request headers.")
            return
        try:
            from ytmusicapi import YTMusic
            YTMusic.setup(filepath=self.auth_path, headers_raw=raw)
            self.result_path = self.auth_path
            self.accept()
        except Exception as exc:
            QMessageBox.critical(self, "Error", f"Failed to parse headers:\n{exc}")

    def _pick_file(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Select auth JSON", self.config_dir, "JSON Files (*.json)"
        )
        if path:
            self._selected_file = path
            self._file_label.setText(path)
            self._use_file_btn.setEnabled(True)

    def _use_file(self):
        import shutil
        path = getattr(self, "_selected_file", None)
        if not path:
            return
        dest = os.path.join(self.config_dir, os.path.basename(path))
        if path != dest:
            shutil.copy2(path, dest)
        self.result_path = dest
        self.accept()
